/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct list {
	char item1[20];
	char item2[20];
	char item3[20];
	char item4[20];
	char item5[20];
	char item6[20];
};
typedef struct list list;

struct matrix {
	int a;
	int b;
	int c;
	int d;
};
typedef struct matrix matrix;

#define ADD_PROG 0x31111111
#define ADDS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_merged_list 1
extern  list * get_merged_list_1(list *, CLIENT *);
extern  list * get_merged_list_1_svc(list *, struct svc_req *);
#define get_reverse_string 2
extern  list * get_reverse_string_1(list *, CLIENT *);
extern  list * get_reverse_string_1_svc(list *, struct svc_req *);
#define get_matrix_sum 3
extern  matrix * get_matrix_sum_1(matrix *, CLIENT *);
extern  matrix * get_matrix_sum_1_svc(matrix *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_merged_list 1
extern  list * get_merged_list_1();
extern  list * get_merged_list_1_svc();
#define get_reverse_string 2
extern  list * get_reverse_string_1();
extern  list * get_reverse_string_1_svc();
#define get_matrix_sum 3
extern  matrix * get_matrix_sum_1();
extern  matrix * get_matrix_sum_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_list (XDR *, list*);
extern  bool_t xdr_matrix (XDR *, matrix*);

#else /* K&R C */
extern bool_t xdr_list ();
extern bool_t xdr_matrix ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
