/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "add.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

list *
get_merged_list_1(list *argp, CLIENT *clnt)
{
	static list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_merged_list,
		(xdrproc_t) xdr_list, (caddr_t) argp,
		(xdrproc_t) xdr_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

list *
get_reverse_string_1(list *argp, CLIENT *clnt)
{
	static list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_reverse_string,
		(xdrproc_t) xdr_list, (caddr_t) argp,
		(xdrproc_t) xdr_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix *
get_matrix_sum_1(matrix *argp, CLIENT *clnt)
{
	static matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_matrix_sum,
		(xdrproc_t) xdr_matrix, (caddr_t) argp,
		(xdrproc_t) xdr_matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
