/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

list *
get_merged_list_1_svc(list *argp, struct svc_req *rqstp)
{
	static list result;

	/*
	 * insert server code here
	 */
	printf("Mergin two lists\n");

	list server;
	strcpy(server.item1, "CSharp");
	strcpy(server.item2, "Java");
	strcpy(server.item3, "Python");

	strcpy(result.item1, server.item1);
	strcpy(result.item2, server.item2);
	strcpy(result.item3, server.item3);
	strcpy(result.item4, argp->item1);
	strcpy(result.item5, argp->item2);
	strcpy(result.item6, argp->item3);

	return &result;
}

list *
get_reverse_string_1_svc(list *argp, struct svc_req *rqstp)
{
	static list result;

	/*
	 * insert server code here
	 */
	printf("Reversing a string\n");

	char temp;
	int i = 0, j = 0;
	j = strlen(argp->item1) - 1;
	while (i < j)
	{
		temp = argp->item1[j];
		result.item1[j] = argp->item1[i];
		result.item1[i] = temp;
		i++;
		j--;
	}

	return &result;
}

matrix *
get_matrix_sum_1_svc(matrix *argp, struct svc_req *rqstp)
{
	static matrix result;

	/*
	 * insert server code here
	 */
	printf("Adding two matrix\n");

	matrix server;
	server.a = 5;
	server.b = 9;
	server.c = 11;
	server.d = 1;

	result.a = server.a + argp->a;
	result.b = server.b + argp->b;
	result.c = server.c + argp->c;
	result.d = server.d + argp->d;

	return &result;
}
